### PR TITLE
Profile photo upload #41

### PR DESCRIPTION
**Pull request by natey37**
### What this PR does (required):
- This pr hooks up functionality for uploading and deleting a user profile photo
-Backend:
- Created a POST route to /uploadImage/:id (user id)
- Created a POST route to /deleteImage/:key (file key)
- Frontend:
- Create APICalls - uploadPhoto and deletePhoto

### Screenshots / Videos (front-end only):
Screen Shot 2022-02-03 at 7 10 05 PM
Screen Shot 2022-02-03 at 7 10 19 PM

### Any information needed to test this feature (required):
- Can test feature by creating a new user and signing in. Go to the settings tab and go to profile photo page. Upload button should add photo to the page and deleting photo should delete the photo off the page. NEED AWS api keys, contact on slack!

### CODE REVIEW

**Comment by ezeilo-su** [comment]
Hey @natey37, kindly link your ticket.

**Comment by natey37** [comment]
https://github.com/hatchways/team-spearmint/issues/41

**Review by ezeilo-su — CHANGES_REQUESTED** [review]
Good progress on this one. Please have a look at those comments I left for you.

**Review by rajivtitus — COMMENTED** [review]
Since most of the code in this PR is from previous branches, let's work on the comments in the setup and the UI branches. Once done, we can update this branch with the changes and have another look at it 👍🏽

**Comment by rajivtitus** [comment]
@natey37 Please update this branch with the remote main and we can possibly get this approved

**Comment by natey37** [comment]
I believe that the previous branch which got merged already had everything in this pr

**Comment by rajivtitus** [comment]
@natey37 Let's update this branch with the up to date main as some of the changes made in the previous branches aren't yet a part of this branch

**Review by rajivtitus — APPROVED** [review]

**Comment by rajivtitus** [comment]
@natey37 Let's get this merged in whenever you get a chance!

**Pull request merged**
